import { useState, useMemo } from 'react';
import { 
  Plus, Trash2, Edit2, Check, X, Calendar, MapPin, Building2, 
  Globe, AlertTriangle, ChevronLeft, ChevronRight, Info, Save,
  Sun, Briefcase, PartyPopper, UserCheck, Download, Upload
} from 'lucide-react';
import { cn } from '@/lib/utils';

// ============================
// Types
// ============================
type OfficeLocation = 'hk' | 'sz' | 'both';

interface PublicHoliday {
  date: string;
  name_zh: string;
  name_en: string;
  office: OfficeLocation;
  isAutoGenerated: boolean;
}

type CustomDayType = 'saturday_work' | 'company_event' | 'no_report_day';

interface CustomDay {
  id: string;
  date: string;
  type: CustomDayType;
  description: string;
  assignedStaff: string[]; // empty = all staff
  office: OfficeLocation;
  createdBy: string;
  createdAt: string;
}

// ============================
// Auto-generated HK Public Holidays 2025
// ============================
const hkHolidays2025: PublicHoliday[] = [
  { date: '2025-01-01', name_zh: '元旦', name_en: "New Year's Day", office: 'hk', isAutoGenerated: true },
  { date: '2025-01-29', name_zh: '農曆年初一', name_en: 'Lunar New Year Day 1', office: 'hk', isAutoGenerated: true },
  { date: '2025-01-30', name_zh: '農曆年初二', name_en: 'Lunar New Year Day 2', office: 'hk', isAutoGenerated: true },
  { date: '2025-01-31', name_zh: '農曆年初三', name_en: 'Lunar New Year Day 3', office: 'hk', isAutoGenerated: true },
  { date: '2025-02-01', name_zh: '農曆年初四（補假）', name_en: 'Lunar New Year Day 4 (Substitute)', office: 'hk', isAutoGenerated: true },
  { date: '2025-04-04', name_zh: '清明節', name_en: 'Ching Ming Festival', office: 'hk', isAutoGenerated: true },
  { date: '2025-04-18', name_zh: '耶穌受難節', name_en: 'Good Friday', office: 'hk', isAutoGenerated: true },
  { date: '2025-04-19', name_zh: '耶穌受難節翌日', name_en: 'Day after Good Friday', office: 'hk', isAutoGenerated: true },
  { date: '2025-04-21', name_zh: '復活節星期一', name_en: 'Easter Monday', office: 'hk', isAutoGenerated: true },
  { date: '2025-05-01', name_zh: '勞動節', name_en: 'Labour Day', office: 'hk', isAutoGenerated: true },
  { date: '2025-05-05', name_zh: '佛誕', name_en: "Buddha's Birthday", office: 'hk', isAutoGenerated: true },
  { date: '2025-05-31', name_zh: '端午節', name_en: 'Tuen Ng Festival', office: 'hk', isAutoGenerated: true },
  { date: '2025-07-01', name_zh: '香港特別行政區成立紀念日', name_en: 'HKSAR Establishment Day', office: 'hk', isAutoGenerated: true },
  { date: '2025-10-01', name_zh: '國慶日', name_en: 'National Day', office: 'hk', isAutoGenerated: true },
  { date: '2025-10-07', name_zh: '重陽節', name_en: 'Chung Yeung Festival', office: 'hk', isAutoGenerated: true },
  { date: '2025-12-25', name_zh: '聖誕節', name_en: 'Christmas Day', office: 'hk', isAutoGenerated: true },
  { date: '2025-12-26', name_zh: '聖誕節後第一個周日', name_en: 'Boxing Day', office: 'hk', isAutoGenerated: true },
];

// ============================
// Auto-generated Shenzhen/China Public Holidays 2025
// ============================
const szHolidays2025: PublicHoliday[] = [
  { date: '2025-01-01', name_zh: '元旦', name_en: "New Year's Day", office: 'sz', isAutoGenerated: true },
  { date: '2025-01-28', name_zh: '春節（除夕）', name_en: 'CNY Eve', office: 'sz', isAutoGenerated: true },
  { date: '2025-01-29', name_zh: '春節初一', name_en: 'CNY Day 1', office: 'sz', isAutoGenerated: true },
  { date: '2025-01-30', name_zh: '春節初二', name_en: 'CNY Day 2', office: 'sz', isAutoGenerated: true },
  { date: '2025-01-31', name_zh: '春節初三', name_en: 'CNY Day 3', office: 'sz', isAutoGenerated: true },
  { date: '2025-02-01', name_zh: '春節初四', name_en: 'CNY Day 4', office: 'sz', isAutoGenerated: true },
  { date: '2025-02-02', name_zh: '春節初五', name_en: 'CNY Day 5', office: 'sz', isAutoGenerated: true },
  { date: '2025-02-03', name_zh: '春節初六', name_en: 'CNY Day 6', office: 'sz', isAutoGenerated: true },
  { date: '2025-02-04', name_zh: '春節初七', name_en: 'CNY Day 7', office: 'sz', isAutoGenerated: true },
  { date: '2025-04-04', name_zh: '清明節', name_en: 'Qingming Festival', office: 'sz', isAutoGenerated: true },
  { date: '2025-04-05', name_zh: '清明節（連假）', name_en: 'Qingming Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-04-06', name_zh: '清明節（連假）', name_en: 'Qingming Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-01', name_zh: '勞動節', name_en: 'Labour Day', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-02', name_zh: '勞動節（連假）', name_en: 'Labour Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-03', name_zh: '勞動節（連假）', name_en: 'Labour Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-04', name_zh: '勞動節（連假）', name_en: 'Labour Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-05', name_zh: '勞動節（連假）', name_en: 'Labour Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-05-31', name_zh: '端午節', name_en: 'Dragon Boat Festival', office: 'sz', isAutoGenerated: true },
  { date: '2025-06-01', name_zh: '端午節（連假）', name_en: 'Dragon Boat Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-06-02', name_zh: '端午節（連假）', name_en: 'Dragon Boat Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-01', name_zh: '國慶節', name_en: 'National Day', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-02', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-03', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-04', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-05', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-06', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
  { date: '2025-10-07', name_zh: '國慶節（連假）', name_en: 'National Day Holiday', office: 'sz', isAutoGenerated: true },
];

// Mock staff list
const allStaff = [
  { id: 'u1', name: '陳小華', role: 'Designer' },
  { id: 'u2', name: '張偉明', role: 'PM' },
  { id: 'u3', name: '朴賢俊', role: 'Video Editor' },
  { id: 'u4', name: '李芷晴', role: 'Copywriter' },
  { id: 'u5', name: '戴維斯', role: 'Marketing' },
  { id: 'u6', name: '王麗華', role: 'Accountant' },
  { id: 'u7', name: '黃志豪', role: 'Management' },
  { id: 'u8', name: '林美玲', role: 'Designer' },
];

const customDayTypeConfig: Record<CustomDayType, { label: string; icon: React.ElementType; color: string; bg: string; description: string }> = {
  saturday_work: {
    label: '星期六上班',
    icon: Briefcase,
    color: 'text-blue-700',
    bg: 'bg-blue-50 border-blue-200',
    description: '指定員工在此星期六需要上班並匯報',
  },
  company_event: {
    label: '公司活動日',
    icon: PartyPopper,
    color: 'text-purple-700',
    bg: 'bg-purple-50 border-purple-200',
    description: '公司活動日，指定人員不需要做日常匯報',
  },
  no_report_day: {
    label: '免匯報日',
    icon: Sun,
    color: 'text-amber-700',
    bg: 'bg-amber-50 border-amber-200',
    description: '特殊安排，指定人員不需要提交匯報',
  },
};

function formatDateLabel(dateStr: string): string {
  const d = new Date(dateStr);
  const days = ['日', '一', '二', '三', '四', '五', '六'];
  return `${d.getFullYear()}/${d.getMonth() + 1}/${d.getDate()} (${days[d.getDay()]})`;
}

function formatMonthYear(year: number, month: number): string {
  return `${year}年${month + 1}月`;
}

// ============================
// Main Component
// ============================
export function HolidaySettings() {
  const [selectedYear, setSelectedYear] = useState(2025);
  const [officeFilter, setOfficeFilter] = useState<'all' | 'hk' | 'sz'>('all');
  const [activeTab, setActiveTab] = useState<'calendar' | 'holidays' | 'custom'>('calendar');
  const [calendarMonth, setCalendarMonth] = useState(new Date().getMonth());

  // Custom days state (admin-managed)
  const [customDays, setCustomDays] = useState<CustomDay[]>([
    {
      id: 'cd1',
      date: '2025-01-25',
      type: 'saturday_work',
      description: '年度盤點日 — 全體需上班',
      assignedStaff: [],
      office: 'both',
      createdBy: '黃志豪',
      createdAt: '2025-01-10',
    },
    {
      id: 'cd2',
      date: '2025-03-15',
      type: 'company_event',
      description: '公司週年慶活動',
      assignedStaff: [],
      office: 'both',
      createdBy: '黃志豪',
      createdAt: '2025-02-20',
    },
    {
      id: 'cd3',
      date: '2025-06-14',
      type: 'saturday_work',
      description: '大型展覽佈置 — 設計+影片團隊',
      assignedStaff: ['u1', 'u3', 'u8'],
      office: 'hk',
      createdBy: '張偉明',
      createdAt: '2025-06-01',
    },
    {
      id: 'cd4',
      date: '2025-08-08',
      type: 'no_report_day',
      description: 'Team Building 活動日',
      assignedStaff: [],
      office: 'both',
      createdBy: '黃志豪',
      createdAt: '2025-07-15',
    },
    {
      id: 'cd5',
      date: '2025-12-24',
      type: 'no_report_day',
      description: '聖誕前夕 — 下午半日假',
      assignedStaff: [],
      office: 'hk',
      createdBy: '黃志豪',
      createdAt: '2025-12-01',
    },
  ]);

  // Add/edit modal
  const [showAddModal, setShowAddModal] = useState(false);
  const [editingDay, setEditingDay] = useState<CustomDay | null>(null);
  const [formDate, setFormDate] = useState('');
  const [formType, setFormType] = useState<CustomDayType>('saturday_work');
  const [formDescription, setFormDescription] = useState('');
  const [formOffice, setFormOffice] = useState<OfficeLocation>('both');
  const [formStaff, setFormStaff] = useState<string[]>([]);

  // Combined holidays
  const allPublicHolidays = useMemo(() => {
    let holidays = [...hkHolidays2025, ...szHolidays2025];
    if (officeFilter !== 'all') {
      holidays = holidays.filter(h => h.office === officeFilter);
    }
    // Deduplicate by date+office
    const seen = new Set<string>();
    return holidays.filter(h => {
      const key = `${h.date}-${h.office}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    }).sort((a, b) => a.date.localeCompare(b.date));
  }, [officeFilter]);

  const filteredCustomDays = useMemo(() => {
    return customDays
      .filter(d => officeFilter === 'all' || d.office === 'both' || d.office === officeFilter)
      .sort((a, b) => a.date.localeCompare(b.date));
  }, [customDays, officeFilter]);

  // Stats
  const stats = useMemo(() => {
    const hkCount = hkHolidays2025.length;
    const szCount = szHolidays2025.length;
    const satWorkCount = customDays.filter(d => d.type === 'saturday_work').length;
    const eventCount = customDays.filter(d => d.type === 'company_event').length;
    const noReportCount = customDays.filter(d => d.type === 'no_report_day').length;
    return { hkCount, szCount, satWorkCount, eventCount, noReportCount, totalCustom: customDays.length };
  }, [customDays]);

  // Calendar data for current month
  const calendarData = useMemo(() => {
    const year = selectedYear;
    const month = calendarMonth;
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startOffset = firstDay.getDay(); // 0=Sun
    
    const days: Array<{
      date: string;
      day: number;
      isCurrentMonth: boolean;
      isToday: boolean;
      isWeekend: boolean;
      isSaturday: boolean;
      holidays: PublicHoliday[];
      customDays: CustomDay[];
    }> = [];

    // Previous month padding
    const prevMonthLast = new Date(year, month, 0).getDate();
    for (let i = startOffset - 1; i >= 0; i--) {
      const d = prevMonthLast - i;
      const dateStr = new Date(year, month - 1, d).toISOString().split('T')[0];
      days.push({
        date: dateStr,
        day: d,
        isCurrentMonth: false,
        isToday: false,
        isWeekend: false,
        isSaturday: false,
        holidays: [],
        customDays: [],
      });
    }

    // Current month
    const today = new Date().toISOString().split('T')[0];
    for (let d = 1; d <= lastDay.getDate(); d++) {
      const dateObj = new Date(year, month, d);
      const dateStr = dateObj.toISOString().split('T')[0];
      const dayOfWeek = dateObj.getDay();
      
      const matchingHolidays = allPublicHolidays.filter(h => h.date === dateStr);
      const matchingCustom = filteredCustomDays.filter(c => c.date === dateStr);
      
      days.push({
        date: dateStr,
        day: d,
        isCurrentMonth: true,
        isToday: dateStr === today,
        isWeekend: dayOfWeek === 0 || dayOfWeek === 6,
        isSaturday: dayOfWeek === 6,
        holidays: matchingHolidays,
        customDays: matchingCustom,
      });
    }

    // Next month padding to fill 6 rows
    const remaining = 42 - days.length;
    for (let d = 1; d <= remaining; d++) {
      const dateStr = new Date(year, month + 1, d).toISOString().split('T')[0];
      days.push({
        date: dateStr,
        day: d,
        isCurrentMonth: false,
        isToday: false,
        isWeekend: false,
        isSaturday: false,
        holidays: [],
        customDays: [],
      });
    }

    return days;
  }, [selectedYear, calendarMonth, allPublicHolidays, filteredCustomDays]);

  // Handlers
  const openAddModal = (prefilledDate?: string) => {
    setEditingDay(null);
    setFormDate(prefilledDate || '');
    setFormType('saturday_work');
    setFormDescription('');
    setFormOffice('both');
    setFormStaff([]);
    setShowAddModal(true);
  };

  const openEditModal = (day: CustomDay) => {
    setEditingDay(day);
    setFormDate(day.date);
    setFormType(day.type);
    setFormDescription(day.description);
    setFormOffice(day.office);
    setFormStaff(day.assignedStaff);
    setShowAddModal(true);
  };

  const handleSave = () => {
    if (!formDate || !formDescription) return;
    
    if (editingDay) {
      setCustomDays(prev => prev.map(d => 
        d.id === editingDay.id 
          ? { ...d, date: formDate, type: formType, description: formDescription, office: formOffice, assignedStaff: formStaff }
          : d
      ));
    } else {
      const newDay: CustomDay = {
        id: `cd${Date.now()}`,
        date: formDate,
        type: formType,
        description: formDescription,
        assignedStaff: formStaff,
        office: formOffice,
        createdBy: '黃志豪',
        createdAt: new Date().toISOString().split('T')[0],
      };
      setCustomDays(prev => [...prev, newDay]);
    }
    setShowAddModal(false);
  };

  const handleDelete = (id: string) => {
    setCustomDays(prev => prev.filter(d => d.id !== id));
  };

  const toggleStaff = (staffId: string) => {
    setFormStaff(prev => 
      prev.includes(staffId) ? prev.filter(s => s !== staffId) : [...prev, staffId]
    );
  };

  return (
    <div className="space-y-4">
      {/* Stats Bar */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        <div className="bg-white rounded-lg border border-red-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[18px]">🇭🇰</span>
            <span className="text-[11px] font-medium text-muted-foreground">香港公眾假期</span>
          </div>
          <span className="text-[22px] font-bold text-red-600">{stats.hkCount}</span>
          <span className="text-[11px] text-muted-foreground ml-1">天</span>
        </div>
        <div className="bg-white rounded-lg border border-red-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[18px]">🇨🇳</span>
            <span className="text-[11px] font-medium text-muted-foreground">深圳法定假日</span>
          </div>
          <span className="text-[22px] font-bold text-red-600">{stats.szCount}</span>
          <span className="text-[11px] text-muted-foreground ml-1">天</span>
        </div>
        <div className="bg-white rounded-lg border border-blue-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <Briefcase size={14} className="text-blue-600" />
            <span className="text-[11px] font-medium text-muted-foreground">星期六上班日</span>
          </div>
          <span className="text-[22px] font-bold text-blue-600">{stats.satWorkCount}</span>
          <span className="text-[11px] text-muted-foreground ml-1">天</span>
        </div>
        <div className="bg-white rounded-lg border border-purple-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <PartyPopper size={14} className="text-purple-600" />
            <span className="text-[11px] font-medium text-muted-foreground">公司活動日</span>
          </div>
          <span className="text-[22px] font-bold text-purple-600">{stats.eventCount}</span>
          <span className="text-[11px] text-muted-foreground ml-1">天</span>
        </div>
        <div className="bg-white rounded-lg border border-amber-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <Sun size={14} className="text-amber-600" />
            <span className="text-[11px] font-medium text-muted-foreground">免匯報日</span>
          </div>
          <span className="text-[22px] font-bold text-amber-600">{stats.noReportCount}</span>
          <span className="text-[11px] text-muted-foreground ml-1">天</span>
        </div>
        <div className="bg-white rounded-lg border border-teal-200 px-4 py-3">
          <div className="flex items-center gap-2 mb-1">
            <Calendar size={14} className="text-teal-600" />
            <span className="text-[11px] font-medium text-muted-foreground">自訂總計</span>
          </div>
          <span className="text-[22px] font-bold text-teal-600">{stats.totalCustom}</span>
          <span className="text-[11px] text-muted-foreground ml-1">條</span>
        </div>
      </div>

      {/* Filter Bar + Tabs */}
      <div className="bg-white rounded-lg border border-border px-5 py-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div className="flex items-center gap-2">
          {/* Tabs */}
          <div className="flex bg-muted rounded-md p-0.5">
            {[
              { id: 'calendar' as const, label: '📅 日曆總覽', icon: Calendar },
              { id: 'holidays' as const, label: '🏖️ 公眾假期', icon: Globe },
              { id: 'custom' as const, label: '⚙️ 自訂日設定', icon: Building2 },
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  'px-3 py-1.5 rounded text-[12px] font-medium transition-all',
                  activeTab === tab.id ? 'bg-white shadow-sm text-teal-800' : 'text-muted-foreground hover:text-foreground'
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
        
        <div className="flex items-center gap-3">
          {/* Office filter */}
          <div className="flex items-center gap-1 bg-muted rounded-md p-0.5">
            {[
              { id: 'all' as const, label: '全部' },
              { id: 'hk' as const, label: '🇭🇰 香港' },
              { id: 'sz' as const, label: '🇨🇳 深圳' },
            ].map(opt => (
              <button
                key={opt.id}
                onClick={() => setOfficeFilter(opt.id)}
                className={cn(
                  'px-2.5 py-1 rounded text-[11px] font-medium transition-all',
                  officeFilter === opt.id ? 'bg-white shadow-sm text-teal-700' : 'text-muted-foreground hover:text-foreground'
                )}
              >
                {opt.label}
              </button>
            ))}
          </div>

          {/* Year selector */}
          <select 
            value={selectedYear} 
            onChange={(e) => setSelectedYear(Number(e.target.value))}
            className="px-2.5 py-1.5 border border-border rounded-md text-[12px] bg-white"
          >
            <option value={2024}>2024年</option>
            <option value={2025}>2025年</option>
            <option value={2026}>2026年</option>
          </select>

          {activeTab === 'custom' && (
            <button 
              onClick={() => openAddModal()} 
              className="flex items-center gap-1.5 px-3 py-1.5 bg-teal-600 text-white rounded-md text-[12px] font-medium hover:bg-teal-700 transition-colors"
            >
              <Plus size={14} />
              新增自訂日
            </button>
          )}
        </div>
      </div>

      {/* Content */}
      {activeTab === 'calendar' && (
        <CalendarView
          calendarData={calendarData}
          calendarMonth={calendarMonth}
          selectedYear={selectedYear}
          onPrevMonth={() => setCalendarMonth(prev => prev === 0 ? 11 : prev - 1)}
          onNextMonth={() => setCalendarMonth(prev => prev === 11 ? 0 : prev + 1)}
          onToday={() => setCalendarMonth(new Date().getMonth())}
          onAddCustomDay={(date) => openAddModal(date)}
        />
      )}

      {activeTab === 'holidays' && (
        <HolidayList holidays={allPublicHolidays} />
      )}

      {activeTab === 'custom' && (
        <CustomDaysList
          customDays={filteredCustomDays}
          onEdit={openEditModal}
          onDelete={handleDelete}
        />
      )}

      {/* Add/Edit Modal */}
      {showAddModal && (
        <AddEditModal
          isEditing={!!editingDay}
          formDate={formDate}
          formType={formType}
          formDescription={formDescription}
          formOffice={formOffice}
          formStaff={formStaff}
          onDateChange={setFormDate}
          onTypeChange={setFormType}
          onDescriptionChange={setFormDescription}
          onOfficeChange={setFormOffice}
          onToggleStaff={toggleStaff}
          onSave={handleSave}
          onCancel={() => setShowAddModal(false)}
        />
      )}

      {/* Legend / Info */}
      <div className="bg-white rounded-lg border border-border px-5 py-3">
        <div className="flex items-center gap-2 mb-2">
          <Info size={13} className="text-muted-foreground" />
          <span className="text-[12px] font-semibold text-muted-foreground">說明</span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-[11px] text-muted-foreground">
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded bg-red-100 border border-red-300 inline-block" />
            <span>公眾假期 — 系統自動載入香港/深圳官方假期，員工於該日無需匯報</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded bg-blue-100 border border-blue-300 inline-block" />
            <span>星期六上班 — Admin 指定的週六加班日，指定人員需要提交匯報</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded bg-purple-100 border border-purple-300 inline-block" />
            <span>公司活動日 — 公司舉辦活動，指定人員不需要做日常匯報</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded bg-amber-100 border border-amber-300 inline-block" />
            <span>免匯報日 — 特殊安排的免匯報日，如 Team Building、半日假等</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ============================
// Calendar View Sub-component
// ============================
function CalendarView({ 
  calendarData, calendarMonth, selectedYear, 
  onPrevMonth, onNextMonth, onToday, onAddCustomDay 
}: {
  calendarData: Array<{
    date: string; day: number; isCurrentMonth: boolean; isToday: boolean;
    isWeekend: boolean; isSaturday: boolean; holidays: PublicHoliday[]; customDays: CustomDay[];
  }>;
  calendarMonth: number;
  selectedYear: number;
  onPrevMonth: () => void;
  onNextMonth: () => void;
  onToday: () => void;
  onAddCustomDay: (date: string) => void;
}) {
  const weekDays = ['日', '一', '二', '三', '四', '五', '六'];

  return (
    <div className="bg-white rounded-lg border border-border overflow-hidden">
      {/* Calendar Header */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-border">
        <div className="flex items-center gap-3">
          <button onClick={onPrevMonth} className="p-1.5 hover:bg-muted rounded-md transition-colors">
            <ChevronLeft size={16} />
          </button>
          <span className="text-[16px] font-bold min-w-[120px] text-center">
            {formatMonthYear(selectedYear, calendarMonth)}
          </span>
          <button onClick={onNextMonth} className="p-1.5 hover:bg-muted rounded-md transition-colors">
            <ChevronRight size={16} />
          </button>
        </div>
        <button 
          onClick={onToday}
          className="px-3 py-1 text-[11px] font-medium bg-teal-50 text-teal-700 rounded-md hover:bg-teal-100 transition-colors border border-teal-200"
        >
          今天
        </button>
      </div>

      {/* Weekday headers */}
      <div className="grid grid-cols-7 border-b border-border">
        {weekDays.map((day, i) => (
          <div key={day} className={cn(
            'text-center py-2 text-[11px] font-semibold',
            i === 0 ? 'text-red-500' : i === 6 ? 'text-blue-500' : 'text-muted-foreground'
          )}>
            {day}
          </div>
        ))}
      </div>

      {/* Calendar Grid */}
      <div className="grid grid-cols-7">
        {calendarData.map((day, i) => {
          const hasHoliday = day.holidays.length > 0;
          const hasCustom = day.customDays.length > 0;
          const hasSatWork = day.customDays.some(c => c.type === 'saturday_work');
          const hasEvent = day.customDays.some(c => c.type === 'company_event');
          const hasNoReport = day.customDays.some(c => c.type === 'no_report_day');

          return (
            <div
              key={`${day.date}-${i}`}
              className={cn(
                'min-h-[90px] border-b border-r border-border/50 p-1.5 relative group transition-colors',
                !day.isCurrentMonth && 'bg-gray-50/50',
                day.isToday && 'bg-teal-50/40',
                hasHoliday && day.isCurrentMonth && 'bg-red-50/30',
                hasSatWork && day.isCurrentMonth && 'bg-blue-50/30',
                hasEvent && day.isCurrentMonth && 'bg-purple-50/30',
                hasNoReport && day.isCurrentMonth && 'bg-amber-50/30',
              )}
            >
              {/* Day number */}
              <div className="flex items-center justify-between mb-0.5">
                <span className={cn(
                  'text-[13px] font-medium w-6 h-6 flex items-center justify-center rounded-full',
                  !day.isCurrentMonth && 'text-gray-300',
                  day.isToday && 'bg-teal-600 text-white',
                  day.isWeekend && day.isCurrentMonth && !day.isToday && 'text-red-400',
                  day.isSaturday && day.isCurrentMonth && !day.isToday && 'text-blue-400',
                )}>
                  {day.day}
                </span>
                {day.isCurrentMonth && (
                  <button 
                    onClick={() => onAddCustomDay(day.date)}
                    className="opacity-0 group-hover:opacity-100 w-5 h-5 flex items-center justify-center rounded bg-teal-100 text-teal-700 hover:bg-teal-200 transition-all"
                  >
                    <Plus size={10} />
                  </button>
                )}
              </div>

              {/* Holiday badges */}
              {hasHoliday && day.isCurrentMonth && day.holidays.map((h, idx) => (
                <div key={idx} className="flex items-center gap-0.5 mb-0.5">
                  <span className="text-[9px] px-1 py-0 rounded bg-red-100 text-red-700 font-medium truncate max-w-full">
                    {h.office === 'hk' ? '🇭🇰' : '🇨🇳'} {h.name_zh}
                  </span>
                </div>
              ))}

              {/* Custom day badges */}
              {hasCustom && day.isCurrentMonth && day.customDays.map((c, idx) => {
                const config = customDayTypeConfig[c.type];
                return (
                  <div key={idx} className="flex items-center gap-0.5 mb-0.5">
                    <span className={cn(
                      'text-[9px] px-1 py-0 rounded font-medium truncate max-w-full border',
                      config.bg, config.color
                    )}>
                      {config.label.slice(0, 4)}
                    </span>
                  </div>
                );
              })}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ============================
// Holiday List Sub-component
// ============================
function HolidayList({ holidays }: { holidays: PublicHoliday[] }) {
  const grouped = useMemo(() => {
    const groups: Record<string, PublicHoliday[]> = {};
    holidays.forEach(h => {
      const month = new Date(h.date).getMonth();
      const key = `${month}`;
      if (!groups[key]) groups[key] = [];
      groups[key].push(h);
    });
    return groups;
  }, [holidays]);

  const monthNames = ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'];

  return (
    <div className="space-y-3">
      {Object.entries(grouped).sort(([a], [b]) => Number(a) - Number(b)).map(([monthKey, holidays]) => (
        <div key={monthKey} className="bg-white rounded-lg border border-border overflow-hidden">
          <div className="px-4 py-2.5 bg-red-50/50 border-b border-red-100">
            <span className="text-[13px] font-bold text-red-800">{monthNames[Number(monthKey)]}</span>
            <span className="text-[11px] text-red-600 ml-2">共 {holidays.length} 天</span>
          </div>
          <div className="divide-y divide-border/50">
            {holidays.map((h, idx) => (
              <div key={idx} className="flex items-center px-4 py-2.5 hover:bg-muted/30 transition-colors">
                <span className="text-[12px] font-mono text-muted-foreground w-[100px]">{h.date}</span>
                <span className="text-[12px] font-medium text-foreground flex-1">{h.name_zh}</span>
                <span className="text-[11px] text-muted-foreground flex-1">{h.name_en}</span>
                <span className={cn(
                  'text-[10px] px-2 py-0.5 rounded-full font-medium',
                  h.office === 'hk' ? 'bg-blue-50 text-blue-700 border border-blue-200' : 'bg-red-50 text-red-700 border border-red-200'
                )}>
                  {h.office === 'hk' ? '🇭🇰 香港' : '🇨🇳 深圳'}
                </span>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// ============================
// Custom Days List Sub-component
// ============================
function CustomDaysList({ 
  customDays, onEdit, onDelete 
}: { 
  customDays: CustomDay[]; 
  onEdit: (day: CustomDay) => void; 
  onDelete: (id: string) => void;
}) {
  return (
    <div className="space-y-3">
      {customDays.length === 0 ? (
        <div className="bg-white rounded-lg border border-border px-6 py-12 text-center">
          <Calendar size={36} className="mx-auto text-muted-foreground/40 mb-3" />
          <p className="text-[14px] font-medium text-muted-foreground">尚未設定自訂日</p>
          <p className="text-[12px] text-muted-foreground/70 mt-1">點擊「新增自訂日」來設定星期六上班、公司活動日或免匯報日</p>
        </div>
      ) : (
        customDays.map(day => {
          const config = customDayTypeConfig[day.type];
          const TypeIcon = config.icon;
          const assignedNames = day.assignedStaff.length > 0 
            ? day.assignedStaff.map(id => allStaff.find(s => s.id === id)?.name || id).join('、')
            : '全體員工';

          return (
            <div key={day.id} className={cn('bg-white rounded-lg border px-5 py-4', config.bg.replace('bg-', 'border-').replace('50', '200'))}>
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <div className={cn('w-9 h-9 rounded-lg flex items-center justify-center mt-0.5', config.bg)}>
                    <TypeIcon size={16} className={config.color} />
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={cn('text-[11px] px-2 py-0.5 rounded-full font-medium border', config.bg, config.color)}>
                        {config.label}
                      </span>
                      <span className="text-[12px] font-mono text-muted-foreground">{formatDateLabel(day.date)}</span>
                      <span className={cn(
                        'text-[10px] px-1.5 py-0.5 rounded-full border',
                        day.office === 'hk' ? 'bg-blue-50 text-blue-600 border-blue-200' :
                        day.office === 'sz' ? 'bg-red-50 text-red-600 border-red-200' :
                        'bg-gray-50 text-gray-600 border-gray-200'
                      )}>
                        {day.office === 'hk' ? '🇭🇰 香港' : day.office === 'sz' ? '🇨🇳 深圳' : '🌐 兩地'}
                      </span>
                    </div>
                    <p className="text-[13px] font-medium text-foreground">{day.description}</p>
                    <div className="flex items-center gap-2 mt-1.5">
                      <UserCheck size={11} className="text-muted-foreground" />
                      <span className="text-[11px] text-muted-foreground">
                        適用：{assignedNames}
                      </span>
                    </div>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] text-muted-foreground/60">
                        由 {day.createdBy} 於 {day.createdAt} 建立
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-1">
                  <button 
                    onClick={() => onEdit(day)} 
                    className="p-1.5 hover:bg-muted rounded-md transition-colors text-muted-foreground hover:text-foreground"
                  >
                    <Edit2 size={13} />
                  </button>
                  <button 
                    onClick={() => onDelete(day.id)} 
                    className="p-1.5 hover:bg-red-50 rounded-md transition-colors text-muted-foreground hover:text-red-600"
                  >
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>
            </div>
          );
        })
      )}
    </div>
  );
}

// ============================
// Add/Edit Modal
// ============================
function AddEditModal({
  isEditing, formDate, formType, formDescription, formOffice, formStaff,
  onDateChange, onTypeChange, onDescriptionChange, onOfficeChange, onToggleStaff,
  onSave, onCancel
}: {
  isEditing: boolean;
  formDate: string;
  formType: CustomDayType;
  formDescription: string;
  formOffice: OfficeLocation;
  formStaff: string[];
  onDateChange: (v: string) => void;
  onTypeChange: (v: CustomDayType) => void;
  onDescriptionChange: (v: string) => void;
  onOfficeChange: (v: OfficeLocation) => void;
  onToggleStaff: (id: string) => void;
  onSave: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="fixed inset-0 m-0 bg-black/40 z-[100] flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-[560px] max-h-[90vh] overflow-hidden flex flex-col">
        <div className="px-6 py-4 border-b border-border flex items-center justify-between shrink-0">
          <h3 className="text-[16px] font-bold">{isEditing ? '編輯自訂日' : '新增自訂日'}</h3>
          <button onClick={onCancel} className="p-1 hover:bg-muted rounded-md transition-colors">
            <X size={18} />
          </button>
        </div>

        <div className="px-6 py-5 space-y-4 flex-1 min-h-0 overflow-y-auto">
          {/* Date */}
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">日期 *</label>
            <input 
              type="date" 
              value={formDate} 
              onChange={(e) => onDateChange(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-md text-[13px] bg-white focus:ring-2 focus:ring-teal-200 focus:border-teal-400"
            />
          </div>

          {/* Type */}
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">類型 *</label>
            <div className="grid grid-cols-3 gap-2">
              {(Object.entries(customDayTypeConfig) as [CustomDayType, typeof customDayTypeConfig[CustomDayType]][]).map(([key, config]) => {
                const Icon = config.icon;
                return (
                  <button
                    key={key}
                    onClick={() => onTypeChange(key)}
                    className={cn(
                      'flex flex-col items-center gap-1.5 px-3 py-3 rounded-lg border-2 transition-all text-center',
                      formType === key 
                        ? `${config.bg} ${config.color} border-current shadow-sm` 
                        : 'border-border bg-white hover:bg-muted/50'
                    )}
                  >
                    <Icon size={18} className={formType === key ? config.color : 'text-muted-foreground'} />
                    <span className="text-[11px] font-medium">{config.label}</span>
                  </button>
                );
              })}
            </div>
            <p className="text-[11px] text-muted-foreground mt-1.5">
              {customDayTypeConfig[formType].description}
            </p>
          </div>

          {/* Description */}
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">說明 *</label>
            <input 
              type="text" 
              value={formDescription} 
              onChange={(e) => onDescriptionChange(e.target.value)}
              placeholder="例如：年度盤點日、公司週年慶、Team Building..."
              className="w-full px-3 py-2 border border-border rounded-md text-[13px] bg-white focus:ring-2 focus:ring-teal-200 focus:border-teal-400"
            />
          </div>

          {/* Office */}
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">適用辦公室</label>
            <div className="flex gap-2">
              {[
                { id: 'both' as const, label: '🌐 兩地通用' },
                { id: 'hk' as const, label: '🇭🇰 僅香港' },
                { id: 'sz' as const, label: '🇨🇳 僅深圳' },
              ].map(opt => (
                <button
                  key={opt.id}
                  onClick={() => onOfficeChange(opt.id)}
                  className={cn(
                    'px-3 py-1.5 rounded-md text-[12px] font-medium border transition-all',
                    formOffice === opt.id 
                      ? 'bg-teal-50 text-teal-700 border-teal-300' 
                      : 'bg-white text-muted-foreground border-border hover:bg-muted/50'
                  )}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          {/* Staff Assignment */}
          <div>
            <label className="text-[12px] font-semibold text-muted-foreground block mb-1.5">
              指定員工
              <span className="font-normal text-[11px] ml-1">（不選 = 全體員工適用）</span>
            </label>
            <div className="grid grid-cols-2 gap-1.5 max-h-[160px] overflow-y-auto border border-border rounded-md p-2">
              {allStaff.map(staff => (
                <button
                  key={staff.id}
                  onClick={() => onToggleStaff(staff.id)}
                  className={cn(
                    'flex items-center gap-2 px-2.5 py-1.5 rounded-md text-[12px] transition-all border',
                    formStaff.includes(staff.id) 
                      ? 'bg-teal-50 text-teal-700 border-teal-300' 
                      : 'bg-white text-muted-foreground border-transparent hover:bg-muted/50'
                  )}
                >
                  <div className={cn(
                    'w-4 h-4 rounded border flex items-center justify-center',
                    formStaff.includes(staff.id) ? 'bg-teal-600 border-teal-600' : 'border-gray-300'
                  )}>
                    {formStaff.includes(staff.id) && <Check size={10} className="text-white" />}
                  </div>
                  <span className="font-medium">{staff.name}</span>
                  <span className="text-[10px] text-muted-foreground/70">{staff.role}</span>
                </button>
              ))}
            </div>
            {formStaff.length === 0 && (
              <p className="text-[11px] text-amber-600 mt-1 flex items-center gap-1">
                <AlertTriangle size={10} />
                未選擇任何員工 = 全體員工適用
              </p>
            )}
          </div>
        </div>

        <div className="px-6 py-3 border-t border-border flex items-center justify-end gap-2 shrink-0 bg-white">
          <button 
            onClick={onCancel}
            className="px-4 py-2 text-[12px] font-medium text-muted-foreground hover:bg-muted rounded-md transition-colors"
          >
            取消
          </button>
          <button
            onClick={onSave}
            disabled={!formDate || !formDescription}
            className={cn(
              'flex items-center gap-1.5 px-4 py-2 rounded-md text-[12px] font-medium transition-colors',
              formDate && formDescription
                ? 'bg-teal-600 text-white hover:bg-teal-700'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed'
            )}
          >
            <Save size={13} />
            {isEditing ? '更新' : '儲存'}
          </button>
        </div>
      </div>
    </div>
  );
}
