#!/usr/bin/env node
/**
 * Prefer dedicated MPS secrets over shared multi-project VITE_* injections.
 *
 * Cloud Agents often inherit Furniture/PMS secrets as VITE_SUPABASE_*.
 * When MPS_URL + MPS_ANON are present, write .env.local so Vite/dev/build
 * always target the MPS Supabase project.
 *
 * Secrets (dashboard):
 *   MPS_URL    = https://kwcevjcmdjadhrygjyfp.supabase.co
 *   MPS_ANON   = MPS project anon/public key
 *   MPS_SERVICE (optional, server/agent only — never expose to Vite client)
 */
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MPS_HOST = 'kwcevjcmdjadhrygjyfp.supabase.co';
const root = resolve(process.cwd());
const envLocalPath = resolve(root, '.env.local');

const mpsUrl = (process.env.MPS_URL || '').trim();
const mpsAnon = (process.env.MPS_ANON || '').trim();
const viteUrl = (process.env.VITE_SUPABASE_URL || '').trim();

function isMpsUrl(url) {
  return typeof url === 'string' && url.includes(MPS_HOST);
}

if (!mpsUrl || !mpsAnon) {
  if (isMpsUrl(viteUrl)) {
    console.log('[sync-mps-env] VITE_SUPABASE_URL already points at MPS; nothing to do.');
    process.exit(0);
  }
  console.warn(
    '[sync-mps-env] MPS_URL / MPS_ANON not set. ' +
      'Add them in Cursor Cloud Agents → Secrets (or your deploy env). ' +
      `Expected host: ${MPS_HOST}`,
  );
  if (viteUrl) {
    console.warn(`[sync-mps-env] Current VITE_SUPABASE_URL host is not MPS: ${viteUrl}`);
  }
  process.exit(0);
}

if (!isMpsUrl(mpsUrl)) {
  console.error(`[sync-mps-env] MPS_URL does not look like the MPS project: ${mpsUrl}`);
  process.exit(1);
}

const contents = [
  '# Generated by scripts/sync-mps-env.mjs — do not commit',
  '# Source: MPS_URL + MPS_ANON (dedicated MPS secrets)',
  `VITE_SUPABASE_URL=${mpsUrl}`,
  `VITE_SUPABASE_ANON_KEY=${mpsAnon}`,
  '',
].join('\n');

// Preserve unrelated keys if .env.local already exists
let merged = contents;
if (existsSync(envLocalPath)) {
  const prev = readFileSync(envLocalPath, 'utf8');
  const keep = prev
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      if (!t || t.startsWith('#')) return false;
      if (t.startsWith('VITE_SUPABASE_URL=')) return false;
      if (t.startsWith('VITE_SUPABASE_ANON_KEY=')) return false;
      return true;
    });
  merged = contents + (keep.length ? keep.join('\n') + '\n' : '');
}

writeFileSync(envLocalPath, merged, 'utf8');
console.log(`[sync-mps-env] Wrote ${envLocalPath} → ${mpsUrl}`);
